# .goreleaser.yaml
version: 2
project_name: ttylag

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the archives compatible with homebrew
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: ttylag
    repository:
      owner: cbrunnkvist
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/cbrunnkvist/ttylag"
    description: "Userspace PTY wrapper that simulates laggy/slow network connections"
    license: "MIT"
    test: |
      system "#{bin}/ttylag", "--version"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
